### PR TITLE
Add testdriven.io

### PR DESCRIPTION
**Pull request by uzza1hossain**

### CODE REVIEW

**Comment by mjhea0** [comment]
You may want to link to [https://testdriven.io/blog/topics/django/](https://testdriven.io/blog/topics/django/) instead, @uzza1hossain.

**Comment by uzza1hossain** [comment]
@mjhea0 Thanks for your suggestion but I added the tips section. Both can be added in a single bracket.

**Comment by theArjun** [comment]
Thanks @mjhea0  for the suggestion. I'm adding that.

**Review by theArjun — CHANGES_REQUESTED** [review]
Add django specific link.

**Comment by uzza1hossain** [comment]
@theArjun link changed

**Pull request merged**
